### ISSUE TITLE
Uncaught TypeError: _templateObject is not a function，

### ISSUE THREAD

**Issue by FrankWang117** [rwjblue/ember-modifier-manager-polyfill#8]
when I use command 
```
 ember s --environment production
```
to run project ,my application will give me this error:
```
Uncaught TypeError: _templateObject is not a function
```
and I find this function in ember-modifier-manager-polyfill.js .
please help me!

**Comment by rwjblue** [comment]
This sounds like a babel transpilation bug, I'm not sure what you are hitting but it seems pretty unlikely that its a bug here in ember-modifier-manager-polyfill.

I'd suggest making a reproduction, and slowly isolating which change causes the error for you.

**Comment by rwjblue** [comment]
Going to close this for now, happy to reopen if you can help me with a reproduction...
